version: '3.8'
services:
  services:
    build: ./apps/services
    container_name: go-backend
    ports:
      - '8080:8080'

  api:
    build: ./apps/api
    container_name: nest-gateway
    ports:
      - '3001:3001'
    depends_on:
      - services
    environment:
      - BACKEND_URL=http://services:8080

  web:
    build: ./apps/web
    container_name: next-frontend
    ports:
      - '3000:3000'
    depends_on:
      - api
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:3001
